### ISSUE TITLE
Crash on server start up

### ISSUE THREAD

**Issue by Cazadorsniper** [Mrthomas20121-Mods/Tinkers-Reforged#2]
Version: 1.0.6
https://pastebin.com/bdkYfSyA

**Comment by Mrthomas20121** [comment]
This was fixed in dev already, the next update should fix it(today i hope)

**Comment by Mrthomas20121** [comment]
https://www.curseforge.com/minecraft/mc-mods/tinkers-reforged/files/2947188 there, this build should fix it

**Comment by Menion01** [comment]
Project Ozone 3 server still crashes even with Reforged 1.1.1 loaded.
